### ISSUE TITLE
Invalid aspect documentation

### ISSUE THREAD

**Issue by sjoerdvisscher** [dwtj/dwtj_rules_markdown#3]
The readme says

    build --aspects @dwtj_rules_markdown//markdown:aspects.bzl%markdownlint_aspect

but the example shows it has to be

    build --aspects @dwtj_rules_markdown//markdown:defs.bzl%markdownlint_aspect

**Comment by sjoerdvisscher** [comment]
Apparently the issue is that the commit hash in the code in the README is old.

**Comment by dwtj** [comment]
Thanks for pointing out this contradiction. It was actually the README that was right. The example was out of date.

So, to enable the aspect in your `.bazelrc`, add

```
build --aspects @dwtj_rules_markdown//markdown:aspects.bzl%markdownlint_aspect
```

With commit c519085, I've fixed this contradiction and bumped the commit hashes.
